import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SidebarApp from "./_components/SidebarApp";
import { SidebarProvider, SidebarTrigger } from "./_components/ui/sidebar";
import { Toaster } from "./_components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} antialiased`}>
        <SidebarProvider>
          <SidebarApp />
          <SidebarTrigger className="hover:cursor-pointer" />
          {children}
        </SidebarProvider>

        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
